repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint --disable C0114,W0223,R0901,W0235,E1101
        language: system
        types: [python]
        require_serial: true
    -   id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
        require_serial: true
